### ISSUE TITLE
Sticky category icons disallow key binding input from Midi QoL

### ISSUE THREAD

**Issue by FreshnessDND** [Drental/fvtt-tokenactionhud#187] opened 2022-03-23 03:40 UTC
After clicking the category or header icon for drop down, the icon is highlighted and stuck. Any key binding input and click of anything in the drop is unsuccessful until you click off and reset the key binding.

**Comment by Larkinabout** [comment] 2022-10-25 02:37
This may have been inadvertently fixed with Token Action HUD being added to the ui.windows object in version 1.0.11 as I'm unable to reproduce the issue. If this issue still occurs, please reopen and provide additionals steps to reproduce.

**Closed by Larkinabout** 2022-10-25 02:37 UTC
Labels: bug
