### ISSUE TITLE
Bug: Extra padding on MAP 1/2 strikes in PF2E leads to line wrapping at scale 1 for 2h weapons

### ISSUE THREAD

**Issue by esheyw** [Drental/fvtt-tokenactionhud#286] opened 2022-09-26 04:41 UTC
This is foundry 10.286, pf2e 4.1.3, TAH 3.0.8, all default settings, only TAH and color picker active.
![image](https://i.imgur.com/MROiqSV.png) ![image](https://i.imgur.com/pG9ZGAh.png)
there are weird right-padding gaps in the 2nd/3rd strike buttons on each line, making lines that get a change grip button wrap the drop button. With no change grip button, no erroneous wrapping:
![image](https://i.imgur.com/6VJTkmE.png)
Scale 0.95 works to get the lines back in place for now, but the gaps are still unsightly.

**Comment by Larkinabout** [comment] 2022-09-28 19:07
This is down to a hardcoded limit on the width of the Strikes category specifically. Easy enough to remove, though I suspect it was put in place to make the Toggles buttons stack as opposed to ending up on one line. I can remove the limit and hopefully we won't get any requests to add it back on!

**Comment by Larkinabout** [comment] 2022-09-28 20:41
Fixed in release 3.0.9.

**Closed by Larkinabout** 2022-09-28 20:41 UTC
Labels: bug

**Comment by esheyw** [comment] 2022-09-28 21:37
Okay so while the lines do now in fact wrap, the problem I was more concerned about was actually the weird padding (Note: I definitely don't know enough about CSS to tell you what the actual properties involved are, i'm just calling it padding for simplicity) on the MAP strike buttons, which is still there. Having just done some checking on v9 latest vs v10 latest, it seems like I noticed it specifically because the DorakoUI themed option in v9 has no padding on the map buttons: ![image](https://i.imgur.com/8UbNCts.png)

The base v9/TAH 2.3.0 styling *does* have some padding, but it centre aligns so it's less immediately noticeable (to me at least): ![image](https://i.imgur.com/pmVOIjm.png)

Whereas in v10/3.0.9 the padding is there in both the Dorako: ![image](https://i.imgur.com/SSCwdY2.png) 
and non-Dorako modes: ![image](https://i.imgur.com/voWpTBx.png)

**Comment by Larkinabout** [comment] 2022-09-28 23:48
Oh, you're talking about the text alignment and the width of the buttons! For a while there I just couldn't see it. I see what you mean about the text alignment. Will sort that for the next release.

In terms of the padding, it was intended to be a bit more forgiving for users that may struggle with click accuracy or are using fingers on touchscreens. The HUD should take up less space while being easier to click the buttons. There could probably be a miminal-width style if there's a strong desire for it. There's also the HUD scale option if you like things generally on the smaller side.

I think the text alignment will make a big difference for your aesthetic pleasure.

If you do get into CSS, it's now pretty easy to add in new styles for other users to enjoy.
