### ISSUE TITLE
Disabled Dropdown Implementation Broken

### ISSUE THREAD

**Issue by Sean-Destefano** [Drental/fvtt-tokenactionhud#310] opened 2022-10-18 03:33 UTC
Disabling the "Dropdown Categories" section now results in the floating menus disappearing on moving the mouse. Using "Click to Open" still works, but otherwise there is no grace area for hovering.

**Comment by Larkinabout** [comment] 2022-10-18 06:50
Duplicate of #308. Will be fixed for the next release.

**Closed** 2022-10-18 06:50 UTC
