### ISSUE TITLE
[Feature Request] Show HUD for default token when player controls no tokens in scene

### ISSUE THREAD

**Issue by nschoenwald** [Drental/fvtt-tokenactionhud#285] opened 2022-09-25 10:06 UTC
It would be very useful for scenes that are just an athmospheric picture, where players won't have their tokens, to still show the Token Action HUD so players can roll their skill checks etc. without opening their character sheets.

**Comment by Larkinabout** [comment] 2022-09-25 10:17
I'm working on this feature currently for 3.1 0. It'll take a little while as it involves rewriting the code for every supported system.

**Comment by nschoenwald** [comment] 2022-09-25 10:19
Awesome, really looking forward to it!

Larkinabout ***@***.***> schrieb am So., 25. Sept. 2022,
12:17:

**Comment by Larkinabout** [comment] 2022-10-03 22:19
Closing as this is a duplicate of #30. This is still in the works for release 3.1.0. Keep on eye on that issue for any updates before release.

**Closed by Larkinabout** 2022-10-03 22:19 UTC
Labels: enhancement, big rework
