### ISSUE TITLE
SW5e (maybe others): Formatting problem causes flickering between two abilities in the actions dropdown

### ISSUE THREAD

**Issue by TogaParty** [Drental/fvtt-tokenactionhud#197] opened 2022-04-05 20:08 UTC
I'm not sure how to describe this, but Token Action HUD is attempting to format an ability between one line and another, causing flickering between two formats in the HUD and making it impossible to tell if you are getting one ability or another before you click.  It's got something to do with the line wrap logic, wherein the module can't decide if it wants the ability on one line or the next.  You see this when you mouse-over an ability as if you are going to click it, but then the button starts flickering and you can't tell which you will get when you click.

Altering the text of an ability name can help, but isn't always practical, depending on the ability.

**Comment by TogaParty** [comment] 2022-04-05 20:10
Also - this seems to depend on the monitor's resolution.  With the same game and character, it occurs with the browser window maximized on my standard monitor, but not my ultra-wide.

**Comment by Larkinabout** [comment] 2022-09-14 21:40
I'm unable to reproduce this issue. Is this issue still happening in the latest release?

**Comment by Larkinabout** [comment] 2022-09-29 13:52
Closing as unable to reproduce in the latest release. Let me know if the issue still exists for you.

**Closed by Larkinabout** 2022-09-29 13:52 UTC
Labels: question
