### ISSUE TITLE
Feature Request: Slightly less compact compact mode

### ISSUE THREAD

**Issue by esheyw** [Drental/fvtt-tokenactionhud#314] opened 2022-10-22 21:37 UTC
First off, I love compact mode, and this is not a dealbreaker, but the spells section on a pf2e character gets just a little too compact, imo:
![image](https://i.imgur.com/RXJYc3A.png)
This actor has 3 spellcasting entries (not uncommon) and as you can see their preceding text is overlapping pretty badly. Not sure exactly what the least-bad solution is (while staying true to the 'compact' idea).

**Comment by Larkinabout** [comment] 2022-10-23 03:00
Yeah, I've seen this before for pf2e. I changed the title to wrap because of the super long titles. We could try making the title font size smaller and/or abbreviating where they hit a limit.

**Comment by esheyw** [comment] 2022-10-23 04:18
I think a little vertical padding between sections so the wrapped text is readable would be fine -- not sure the css difficulty level implied 😓

**Comment by Drental** [comment] 2022-10-23 07:52
the problem is that even in compact mode higher level casters easily need scrolling.

btw, scrolling is awesome!

**Comment by Larkinabout** [comment] 2022-10-25 01:41
This is about the best I can do. Shrunk the text, removed instances of 'Spells' from the subtitles and separated every word into its own div, so it will wrap nicely. I may try to come up with a better solution for subtitles generally, but for now this should help.
![image](https://user-images.githubusercontent.com/105953297/197662299-3d7b30bd-74c7-4622-96c3-39cf0ef2c0e7.png)

**Comment by esheyw** [comment] 2022-10-25 02:14
That looks perfectly serviceable, thanks!

**Comment by Larkinabout** [comment] 2022-10-26 23:09
Fixed in release 3.0.13.

**Closed by Larkinabout** 2022-10-26 23:09 UTC
Labels: bug
