### ISSUE TITLE
Token Action HUD Not Showing All NPC's Spells (5e)

### ISSUE THREAD

**Issue by King-Khufu** [Drental/fvtt-tokenactionhud#191] opened 2022-03-31 03:00 UTC
I cannot get Token Action HUD to show all of the spells that NPC Actors have on them. I use the Character Action List module.

![image](https://user-images.githubusercontent.com/87103761/160967604-e45c5909-712a-4d95-8f22-9aef7f02605a.png)

**Comment by Drental** [comment] 2022-04-11 13:58
can you export the actor and link it in the ticket?

**Comment by Larkinabout** [comment] 2022-09-11 23:59
I'm unable to reproduce this issue on Token Action HUD 3.0.4 andCharacter Actions List dnd5e 6.0.1. Does this issue still exist?

**Comment by Larkinabout** [comment] 2022-09-14 20:55
Closing as unable to reproduce in the latest release. Let me know if it's still an issue.

**Closed by Larkinabout** 2022-09-14 20:55 UTC
