### ISSUE TITLE
enhancement: "Always display HUD" even when the player has no token on the active Scene

### ISSUE THREAD

**Issue by jcolson** [Drental/fvtt-tokenactionhud#101] opened 2021-10-14 12:01 UTC
On larger (map) scenes a DM may use a "Party Token" to show the party's position on the scene/map.  In these scenarios, it is likely that the party may need to make constitution saves, investigation checks, cast a spell, etc... 

but, curremtly, the action hud is not displayed if the player has no token on the scene.

it would be nice to have that configurable (have the token hud display for the player's default actor).

**Comment by Larkinabout** [comment] 2022-10-03 22:16
Closing as this is a duplicate of #30. This is in the works for release 3.1.0.

**Closed by Larkinabout** 2022-10-03 22:16 UTC
Labels: enhancement
