### ISSUE TITLE
Token Action Hud not showing for a Player with Spontaneous Casting - PF1

### ISSUE THREAD

**Issue by KaoSdReapeR** [Drental/fvtt-tokenactionhud#202] opened 2022-04-19 16:30 UTC
![image](https://user-images.githubusercontent.com/9070649/164050972-c1d1f5d7-55cb-4a48-ad58-a1928eb87d01.png)

Everytime the character gets selected that error shows up on the logs.

We already tried to delete all of his spells and even removing the spellcasting from his character but the problem prevails.

All the other characters have magic (prepared casters) and its working on their end.

If I create a new character the HUD works untill the point I start giving him spells.

This is Pathfinder 1.

Thank you.

**Comment by Motara7** [comment] 2022-05-10 00:52
I'm having the same problem with two of my actors. One actor has no spells, but does have spell-like abilities. The other actor has so spells at all. I get the exact same error you show for each of them and no HUD displays. Please let me know if you come up with a solution.

**Comment by Larkinabout** [comment] 2022-09-11 23:37
I have tested but cannot reproduce this error. Is this error still happening for you in the latest version? If so, will you please list the class and spells.

**Comment by Larkinabout** [comment] 2022-09-14 20:57
Closing as unable to reproduce in the latest release. Let me know if it's still an issue.

**Closed by Larkinabout** 2022-09-14 20:57 UTC

**Comment by Motara7** [comment] 2022-09-14 22:29
Sorry I didn't get back to you right away. The problem is happening in a
game where I am a player. The Foundry (9) session is on Forge. I have
ownership rights on several characters (familiar, summoned creatures,
etc.). No matter which token I have selected, HUD only shows the infor for
my PC. Can you think of anything I should have the GM check on?

**Comment by Larkinabout** [comment] 2022-09-15 08:09
Sorry, should have been clearer, all the updates that have likely fixed this issue have been done for Foundry VTT v10. Maybe check with your GM when they plan to upgrade to v10.

**Comment by Motara7** [comment] 2022-09-15 16:32
Thanks! I love your module. It makes playing and GMing so much easier for
me. I also really appreciate you taking the time to respond to my
particular problem.
